# Generated by Django 5.1 on 2024-08-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_address_customer_alter_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.zip"
            ),
        ),
    ]
