# Generated by Django 5.1 on 2024-08-22 19:46

from django.db import migrations


class Migration(migrations.Migration):
 
    dependencies = [
        ("store", "0005_zip_address_zip"),
    ]

    operations = [migrations.RunSQL("""INSERT INTO store_collection (title) 
                                    VALUES ('collection1')
                                    """, """
                                    DELETE FROM store_collection
                                    WHERE title='collection1'
                                    """)]
    
