# Generated by Django 5.1 on 2024-08-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_auto_20240822_1946"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        # migrations.RenameField(
        #     model_name="customer",
        #     old_name="members",
        #     new_name="membership",
        # ),
        migrations.AlterField(
            model_name="order",
            name="placed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
