# Generated by Django 5.1 on 2024-08-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_collection_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="membership",
            field=models.CharField(
                choices=[("B", "Bronze"), ("S", "Silver"), ("G", "Gold")],
                default="B",
                max_length=20,
            ),
        ),
    ]
